# YOU CAN'T USUALLY ADD UP INTEGER TO A STRING SO THE ONLY SOLUTION IS EITHER CONVERTING IN ONE FORMAT IN ORDER TO ADD UP

Birth_year = input('Why is your birth year? ')
# TO SUBTRACT INTEGER TO Birth_year WHICH IS HOLDING A STRING YOU USE int() FUNCTION
AGE = 2024 - int(Birth_year)
print(type(AGE))  # TO IDENTIFY THE TYPE YOU NEED TO USE THE type() FUNCTION
print(AGE)
